# Generated by Django 3.1.3 on 2020-11-11 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_alunos',
            },
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_hora', models.IntegerField()),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_atividades',
            },
        ),
        migrations.CreateModel(
            name='Curriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carga_horaria', models.IntegerField()),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_curriculos',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tbl_cursos',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_professores',
            },
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ehHora', models.BooleanField()),
                ('limite_hora_lancamento', models.IntegerField()),
                ('hora_acg', models.IntegerField()),
                ('hora_praticada', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('nome', models.CharField(max_length=100)),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.atividade')),
                ('curriculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.curriculo')),
            ],
            options={
                'db_table': 'tbl_regras',
            },
        ),
        migrations.CreateModel(
            name='ProfessorCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.curso')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.professor')),
            ],
            options={
                'db_table': 'tbl_cursos_professores',
            },
        ),
        migrations.CreateModel(
            name='Lancamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
                ('arquivo', models.CharField(max_length=100)),
                ('carga_horaria_real', models.IntegerField()),
                ('carga_horaria_acg', models.IntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.aluno')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.regra')),
            ],
            options={
                'db_table': 'tbl_lancamentos',
            },
        ),
        migrations.CreateModel(
            name='CursoCurriculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Curriculo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.curriculo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.curso')),
            ],
            options={
                'db_table': 'tbl_cursos_curriculos',
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='curriculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.curriculo'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.curso'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
