# Generated by Django 3.1.3 on 2020-11-24 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201123_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='curriculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.curriculo'),
        ),
    ]
