# Generated by Django 3.1.3 on 2020-11-26 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201124_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='curriculo',
            name='cursos',
            field=models.ManyToManyField(to='app.Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='curriculos',
            field=models.ManyToManyField(to='app.Curriculo'),
        ),
        migrations.DeleteModel(
            name='CursoCurriculo',
        ),
    ]
