# Generated by Django 3.1.3 on 2020-11-26 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_lancamento_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
