# Generated by Django 3.1.3 on 2020-11-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lancamento_aprovado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lancamento',
            name='aprovado',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
