# Generated by Django 3.1.3 on 2020-11-26 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20201126_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamento',
            name='comentario',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
